trigger:

- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: ArtifactoryCloud
    buildName: $(Build.DefinitionName)
    buildNumber: $(Build.BuildNumber)
- task: ArtifactoryToolsInstaller@1
  inputs:
    artifactoryService: 'ArtifactoryCloud'
    cliInstallationRepo: 'jcenter'
