trigger:
- master
pool:
  vmImage: 'Ubuntu-18.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: ArtifactoryToolsInstaller@1
  inputs:
    artifactoryService: 'Kayal'
    cliInstallationRepo: 'jfrog-cli'
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: docker-local.jfrog.io/$(imageName)
    command: build
    Dockerfile: app/Dockerfile
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: ArtifactoryCloud
    buildName: $(Build.DefinitionName)
    buildNumber: $(Build.BuildNumber)
- task: ArtifactoryXrayScan@1
  inputs:
    artifactoryService: 'ArtifactoryCloud'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: false