trigger:

- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: ArtifactoryToolsInstaller@1
  inputs:
    artifactoryService: 'ArtifactoryCloud'
    cliInstallationRepo: 'tata-cli'
    installExtractors: true
    extractorsInstallationRepo: 'jcenter'
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
- task: ArtifactoryGenericDownload@3
  inputs:
    connection: 'ArtifactoryCloud'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "jcenter/*.*",
            "target": "dependencies/files/"
          }
        ]
      }
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    failNoOp: false
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: ArtifactoryCloud
    buildName: $(Build.DefinitionName)
    buildNumber: $(Build.BuildNumber)
