trigger:
- master
pool:
  vmImage: 'Ubuntu-18.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: ArtifactoryToolsInstaller@1
  inputs:
    artifactoryService: 'ArtifactoryCloud'
    cliInstallationRepo: 'tata-cli'
    installExtractors: true
    extractorsInstallationRepo: 'jcenter'
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: seshu7trail-tata-docker-local.jfrog.io/$(imageName)
    command: build
    Dockerfile: app/Dockerfile
- task: ArtifactoryDocker@1
  inputs:
    command: 'push'
    artifactoryService: 'ArtifactoryCloud'
    targetRepo: 'tata-docker-local'
    imageName: 'seshu7trail-tata-docker-local.jfrog.io/$(imageName):$(Build.BuildId)'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: ArtifactoryCloud
    buildName: $(Build.DefinitionName)
    buildNumber: $(Build.BuildNumber)
- task: ArtifactoryXrayScan@1
  inputs:
    artifactoryService: 'ArtifactoryCloud'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: false
- task: ArtifactoryBuildPromotion@1
  inputs:
    artifactoryService: 'ArtifactoryCloud'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    targetRepo: 'tata-docker-virtual'
    status: 'Released'
    sourceRepo: 'tata-docker-local'
    includeDependencies: true
    copy: false
    dryRun: false